---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/openstack/requirements.yml
    role-file: molecule/openstack/requirements.yml
driver:
  port: 22
  ssh_identity_file: ~/.ssh/med-deployer-dev
platforms:
  - name: beealma810-01
    image: AlmaLinux-8-GenericCloud-8.10
    flavor: m1.medium
    key_name: med-deployer
    volumes: [metafs1, storagefs1]
    meta:
      cloud_user: almalinux
    security_groups:
      - ssh_icmp
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - storage
      - management
      - metadata
      - monitoring
      - clients
  - name: beealma95-01
    image: AlmaLinux-9-GenericCloud-9.5
    flavor: m1.medium
    key_name: med-deployer
    volumes: [metafs2, storagefs2]
    meta:
      cloud_user: almalinux
    security_groups:
      - ssh_icmp
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - storage
      - management
      - metadata
      - monitoring
      - clients
  - name: beeubuntu2204-01
    image: Ubuntu-jammy-22.04
    flavor: m1.medium
    key_name: med-deployer
    volumes: [metafs3, storagefs3]
    meta:
      cloud_user: ubuntu
    security_groups:
      - ssh_icmp
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - storage
      - management
      - metadata
      - monitoring
      - clients
  - name: beealma810-02
    image: AlmaLinux-8-GenericCloud-8.10
    flavor: m1.medium
    key_name: med-deployer
    volumes: [metafs4, storagefs4]
    meta:
      cloud_user: almalinux
    security_groups:
      - ssh_icmp
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - storage
      - management
      - metadata
      - monitoring
      - clients
  - name: beealma95-02
    image: AlmaLinux-9-GenericCloud-9.5
    flavor: m1.medium
    key_name: med-deployer
    volumes: [metafs5, storagefs5]
    meta:
      cloud_user: almalinux
    security_groups:
      - ssh_icmp
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - storage
      - management
      - metadata
      - monitoring
      - clients
  - name: beeubuntu2204-02
    image: Ubuntu-jammy-22.04
    flavor: m1.medium
    key_name: med-deployer
    volumes: [metafs6, storagefs6]
    meta:
      cloud_user: ubuntu
    security_groups:
      - ssh_icmp
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - storage
      - management
      - metadata
      - monitoring
      - clients
provisioner:
  name: ansible
  # needed otherwise molecule does not find it
  env:
    ANSIBLE_ROLES_PATH: ../../../roles/
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
  playbooks:
    create: ../openstack/playbooks/create.yml
    destroy: ../openstack/playbooks/destroy.yml
    converge: ../openstack/playbooks/converge.yml
  inventory:
    host_vars:
      beealma810-01:
        client_clusters:
          - sys_mgmtd_host: localhost
            cluster_storage_nodes: ["beealma810-01"]
            cluster_meta_nodes: ["beealma810-01"]
      beealma95-01:
        mgmtd_string_id: localhost
        client_clusters:
          - sys_mgmtd_host: localhost
            cluster_storage_nodes: ["beealma95-01"]
            cluster_meta_nodes: ["beealma95-01"]
      beealma810-02:
        client_dkms_install: true
        client_clusters:
          - sys_mgmtd_host: localhost
            cluster_storage_nodes: ["beealma810-01"]
            cluster_meta_nodes: ["beealma810-01"]
      beealma95-02:
        client_dkms_install: true
        mgmtd_string_id: localhost
        client_clusters:
          - sys_mgmtd_host: localhost
            cluster_storage_nodes: ["beealma95-01"]
            cluster_meta_nodes: ["beealma95-01"]
      beeubuntu2204-01:
        mgmtd_conn_interfaces: ["ens3"]
        mon_conn_interfaces: ["ens3"]
        metad_server_targets:
          - target_id: 1
            conn_interfaces: ["ens3"]
            sys_mgmtd_host: localhost
        storaged_server_targets:
          - target_id: 1
            conn_interfaces: ["ens3"]
            sys_mgmtd_host: localhost
        client_clusters:
          - sys_mgmtd_host: localhost
            cluster_storage_nodes: ["beeubuntu2204-01"]
            cluster_meta_nodes: ["beeubuntu2204-01"]
      beeubuntu2204-02:
        client_dkms_install: true
        mgmtd_conn_interfaces: ["ens3"]
        mon_conn_interfaces: ["ens3"]
        metad_server_targets:
          - target_id: 1
            conn_interfaces: ["ens3"]
            sys_mgmtd_host: localhost
        storaged_server_targets:
          - target_id: 1
            conn_interfaces: ["ens3"]
            sys_mgmtd_host: localhost
        client_clusters:
          - sys_mgmtd_host: localhost
            conn_interfaces: ["ens3"]
            cluster_storage_nodes: ["beeubuntu2204-01"]
            cluster_meta_nodes: ["beeubuntu2204-01"]
    group_vars:
      all:
        system_beegfs_version: 7.4.6
        mgmtd_conn_interfaces: ["eth0"]
        mon_conn_interfaces: ["eth0"]
      metadata:
        metad_server_targets:
          - target_id: 1
            conn_interfaces: ["eth0"]
            sys_mgmtd_host: localhost
      storage:
        storaged_server_targets:
          - target_id: 1
            conn_interfaces: ["eth0"]
            sys_mgmtd_host: localhost
verifier:
  name: ansible
