---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/openstack/requirements.yml
    role-file: molecule/openstack/requirements.yml
driver:
  port: 22
  ssh_identity_file: ~/.ssh/e4github
platforms:
  - name: beerocky8-01
    image: Rocky-8-GenericCloud-LVM.x86_64
    flavor: m1.medium
    key_name: dobbi
    meta:
      cloud_user: rocky
    availability_zone: nova
    security_groups:
      - ssh_icmp
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - storage
      - management
      - metadata
      - monitoring
      - clients
  - name: beeubuntu2204-01
    image: Ubuntu-jammy-22.04
    flavor: m1.medium
    key_name: dobbi
    meta:
      cloud_user: ubuntu
    availability_zone: nova
    security_groups:
      - ssh_icmp
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - storage
      - management
      - metadata
      - monitoring
      - clients
provisioner:
  name: ansible
  # needed otherwise molecule does not find it
  env:
    ANSIBLE_ROLES_PATH: ../../../roles/
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
  playbooks:
    create: ../openstack/playbooks/create.yml
    destroy: ../openstack/playbooks/destroy.yml
    converge: ../openstack/playbooks/converge.yml
  inventory:
    host_vars:
      beerocky8-01:
        client_clusters:
          - sys_mgmtd_host: localhost
            cluster_storage_nodes: ["beerocky8-01"]
            cluster_meta_nodes: ["beerocky8-01"]
      beeubuntu2204-01:
        client_clusters:
          - sys_mgmtd_host: localhost
            cluster_storage_nodes: ["beeubuntu2204-01"]
            cluster_meta_nodes: ["beeubuntu2204-01"]
    group_vars:
      all:
        system_beegfs_version: 7.4.3
      metadata:
        metad_server_targets:
          - target_id: 1
            sys_mgmtd_host: localhost
      storage:
        storaged_server_targets:
          - target_id: 1
            sys_mgmtd_host: localhost
verifier:
  name: ansible
