---
argument_specs:

  main:
    short_description: Configure Beegfs cluster features
    description:
      - Configure Beegfs cluster features like BuddyMirror, StoragePools and Striping policies.
      - These settings are configured by the use of the `beegfs-ctl` command-line.
    author:
      - Davide Obbi
    version_added: 1.0.0
    options:
      cluster_storage_nodes:
        type: list
        elements: str
        description: The list of the hosts that will run the storage services and hold the storage targets
        default: []
      cluster_meta_nodes:
        type: list
        elements: str
        description: The list of the hosts that will run the metadata services and hold the meta targets
        default: []
      cluster_dir_paths:
        type: list
        elements: dict
        description: The list of directory paths relative to the Beegfs mountpoint with custom striping rules
        default:
          - beegfs_path:
              type: str
              description: The path relative to the Beegfs mountpoint where the directory should exist
              required: true
            fs_path:
              type: str
              description: The path relative to the root filesystem where the directory should be bind mounted
              required: false
            chunk_size:
              type: str
              description: The chunk size to use by the Beegfs striping policy
              required: false
              default: 512K
              choices: ["512K", "1M", "2M"]
            num_targets:
              type: str
              description: The number of desired targets to use by the Beegfs striping policy
              default: 4
              required: false
            pattern:
              type: str
              description: The pattern or protection level to use by the Beegfs striping policy
              required: false
              default: raid0
              choices: ["raid0", "buddymirror"]
            storagepool_id:
              type: str
              default: 1
              description: The storage pool id that should be targeted by the Beegfs triping policy
              required: false
