---
- name: Check authentication file locally present
  ansible.builtin.stat:
    path: "{{ system_auth_file_path }}"
  delegate_to: localhost
  register: _system_auth_file_path_result
  when: system_deploy_auth_file
  become: false
  tags:
    - prechecks

- name: Assert that the authentication file is locally existing
  ansible.builtin.assert:
    that:
      - _system_auth_file_path_result.stat.exists
    success_msg: "File {{ system_auth_file_path }} exists locally"
    fail_msg: "File {{ system_auth_file_path }} does not exists locally"
  when: system_deploy_auth_file
  tags:
    - prechecks
