---
- name: Restart beegfs helperd service
  ansible.builtin.systemd:
    daemon_reload: true
    name: "beegfs-helperd"
    state: restarted
  when:
    - client_start_services
    - not multi_mode
  tags:
    - restart_services

- name: Restart beegfs client service
  ansible.builtin.systemd:
    daemon_reload: true
    name: "beegfs-client"
    state: restarted
  when:
    - client_start_services
    - not multi_mode
    - not client_dkms_install
  tags:
    - restart_services

- name: Restart beegfs helperd@ services
  ansible.builtin.systemd:
    daemon_reload: true
    name: "beegfs-helperd@{{ item.sys_mgmtd_host | replace('-', '') }}"
    state: restarted
  loop: "{{ client_clusters }}"
  when:
    - client_start_services
    - multi_mode
  tags:
    - restart_services

- name: Restart beegfs client@ services
  ansible.builtin.systemd:
    daemon_reload: true
    name: "beegfs-client@{{ item.sys_mgmtd_host | replace('-', '') }}"
    state: restarted
  loop: "{{ client_clusters }}"
  when:
    - client_start_services
    - multi_mode
    - not client_dkms_install
  tags:
    - restart_services

- name: Load beegfs module
  ansible.builtin.command: modprobe beegfs
  changed_when: false
  when:
    - client_dkms_install
  tags:
    - restart_services
