---
- name: Restart beegfs helperd service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "beegfs-helperd"
    state: restarted
  when:
    - client_start_services
    - not multi_mode
    - client_beegfs_version | split('.') | first | int == 7
  tags:
    - restart_services

- name: Restart beegfs client service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "beegfs-client"
    state: restarted
  when:
    - client_start_services
    - not multi_mode
    - not client_dkms_install
    - not ansible_check_mode
  tags:
    - restart_services

- name: Restart beegfs helperd@ services
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "beegfs-helperd@{{ item.sys_mgmtd_host | replace('-', '') }}"
    state: restarted
  loop: "{{ client_clusters }}"
  when:
    - client_start_services
    - multi_mode
    - client_beegfs_version | split('.') | first | int == 7
    - not ansible_check_mode
  tags:
    - restart_services

- name: Restart beegfs client@ services
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "beegfs-client@{{ item.sys_mgmtd_host | replace('-', '') }}"
    state: restarted
  loop: "{{ client_clusters }}"
  when:
    - client_start_services
    - multi_mode
    - not client_dkms_install
    - not ansible_check_mode
  tags:
    - restart_services

- name: Load beegfs module
  become: true
  ansible.builtin.command: modprobe beegfs
  changed_when: false
  when:
    - client_dkms_install
    - not ansible_check_mode
  tags:
    - restart_services
