---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/molecule/openstack/requirements.yml
    role-file: ${MOLECULE_PROJECT_DIRECTORY}/molecule/openstack/requirements.yml
driver:
  port: 22
  ssh_identity_file: ~/.ssh/med-deployer-dev
platforms:
  - name: mgmt-alma95-01
    image: AlmaLinux-9-GenericCloud-9.5
    flavor: m1.medium
    key_name: med-deployer
    volumes: []
    meta:
      cloud_user: almalinux
    security_groups:
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - management
      - monitoring
  - name: stor-alma95-01
    image: AlmaLinux-9-GenericCloud-9.5
    flavor: m1.medium
    key_name: med-deployer
    volumes: [metafs1, storagefs1, metafs3, storagefs3]
    meta:
      cloud_user: almalinux
    security_groups:
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - storage
      - metadata
  - name: stor-alma95-02
    image: AlmaLinux-9-GenericCloud-9.5
    flavor: m1.medium
    key_name: med-deployer
    volumes: [metafs2, storagefs2, metafs4, storagefs4]
    meta:
      cloud_user: almalinux
    security_groups:
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - storage
      - metadata
  - name: cnode-alma95-01
    image: AlmaLinux-9-GenericCloud-9.5
    flavor: m1.medium
    key_name: med-deployer
    volumes: []
    meta:
      cloud_user: almalinux
    security_groups:
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - clients
  - name: cnode-rocky94-02
    image: Rocky-9-GenericCloud-Base.9.4.x86_64
    flavor: m1.medium
    key_name: med-deployer
    volumes: []
    meta:
      cloud_user: rocky
    security_groups:
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - clients
  - name: cnode-alma95-03
    image: AlmaLinux-9-GenericCloud-9.5
    flavor: m1.medium
    key_name: med-deployer
    volumes: []
    meta:
      cloud_user: almalinux
    security_groups:
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - clients
  - name: cnode-ubuntu22-04
    image: Ubuntu-jammy-22.04
    flavor: m1.medium
    key_name: med-deployer
    volumes: []
    meta:
      cloud_user: ubuntu
    security_groups:
      - beegfs
    nics:
      - net-name: private_tech_dev
    external_network: external_1632
    validate_certs: false
    groups:
      - clients
provisioner:
  name: ansible
  # needed otherwise molecule does not find it
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/../roles/
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
  playbooks:
    create: ${MOLECULE_PROJECT_DIRECTORY}/molecule/openstack/playbooks/create.yml
    destroy: ${MOLECULE_PROJECT_DIRECTORY}/molecule/openstack/playbooks/destroy.yml
    converge: ${MOLECULE_PROJECT_DIRECTORY}/molecule/openstack/playbooks/converge.yml
  inventory:
    host_vars:
      mgmt-alma95-01:
        mgmtd_beegfs_version: 7.4.6
        mon_beegfs_version: 7.4.6
        mgmtd_conn_interfaces: ["eth0"]
        mon_conn_interfaces: ["eth0"]
      stor-alma95-01:
        metad_server_targets:
          - target_id: 1
            device: "vdb"
            conn_interfaces: ["eth0"]
            sys_mgmtd_host: mgmt-alma95-01
          - target_id: 3
            device: "vdc"
            conn_interfaces: ["eth0"]
            sys_mgmtd_host: mgmt-alma95-01
        storaged_server_targets:
          - target_id: 1
            device: "vdd"
            conn_interfaces: ["eth0"]
            sys_mgmtd_host: mgmt-alma95-01
          - target_id: 3
            device: "vde"
            conn_interfaces: ["eth0"]
            sys_mgmtd_host: mgmt-alma95-01
      stor-alma95-02:
        metad_server_targets:
          - target_id: 2
            device: "vdb"
            conn_interfaces: ["eth0"]
            sys_mgmtd_host: mgmt-alma95-01
          - target_id: 4
            device: "vdc"
            conn_interfaces: ["eth0"]
            sys_mgmtd_host: mgmt-alma95-01
        storaged_server_targets:
          - target_id: 2
            device: "vdd"
            conn_interfaces: ["eth0"]
            sys_mgmtd_host: mgmt-alma95-01
          - target_id: 4
            device: "vde"
            conn_interfaces: ["eth0"]
            sys_mgmtd_host: mgmt-alma95-01
      cnode-alma95-03:
        client_dkms_install: true
    group_vars:
      metadata:
        metad_beegfs_version: 7.4.6
      storage:
        storaged_beegfs_version: 7.4.6
      clients:
        client_beegfs_version: 7.4.6
        client_clusters:
          - sys_mgmtd_host: mgmt-alma95-01
            client_dir_paths:
              - beegfs_path: home
                fs_path: /usr/home
              - beegfs_path: data/bulk
                fs_path: /bulk
verifier:
  name: ansible
