---
# Client with NVIDIA GPU Direct Support
# Deploy BeeGFS client with NVIDIA GPU Direct Storage for direct GPU memory access
- name: Deploy BeeGFS Clients with GPU Direct
  hosts: gpu_nodes
  become: true
  roles:
    - role: e4_computer_engineering.beegfs.client
      vars:
        client_beegfs_version: "8.1"
        client_rdma_enabled: true
        client_nvfs_libs_path: /usr/src/nvidia-fs
        client_nvidia_libs_path: /usr/src/nvidia
        client_ofed_libs_path: /usr/src/ofa_kernel/default/include
        client_auth_file_path: playbooks/files/conn.auth
        client_clusters:
          - sys_mgmtd_host: mgmt-01
            conn_interfaces: ["ib0"]
            conn_use_rdma: "true"
