---
# Multi-Cluster Client Configuration
# Configure a client to access multiple BeeGFS clusters
- name: Deploy BeeGFS client with multi-cluster support
  hosts: compute_nodes
  become: true
  roles:
    - role: e4_computer_engineering.beegfs.client
      vars:
        client_beegfs_version: "8.1"
        client_auth_file_path: playbooks/files/conn.auth
        client_clusters:
          # First cluster - production data
          - sys_mgmtd_host: mgmt-prod-01
            conn_client_port_udp: "8004"
            conn_helperd_port_tcp: "8006"
            conn_mgmtd_port_tcp: "8008"
            conn_mgmtd_port_udp: "8008"
            conn_interfaces: ["eth0"]
            client_dir_paths:
              - beegfs_path: production
                fs_path: /mnt/beegfs-prod

          # Second cluster - scratch data
          - sys_mgmtd_host: mgmt-scratch-01
            conn_client_port_udp: "8014"
            conn_helperd_port_tcp: "8016"
            conn_mgmtd_port_tcp: "8018"
            conn_mgmtd_port_udp: "8018"
            conn_interfaces: ["eth1"]
            client_dir_paths:
              - beegfs_path: scratch
                fs_path: /scratch
