---
# Single-Node Cluster Deployment
# Deploy all BeeGFS services on a single node for testing or small deployments
- name: Deploy single-node BeeGFS cluster
  hosts: beegfs_all_in_one
  become: true
  vars:
    beegfs_version: "8.1"
    mgmt_host: "{{ inventory_hostname }}"
    auth_file: playbooks/files/conn.auth

  tasks:
    - name: Deploy Management Service
      ansible.builtin.include_role:
        name: e4_computer_engineering.beegfs.mgmtd
      vars:
        mgmtd_beegfs_version: "{{ beegfs_version }}"
        mgmtd_store_mgmtd_directory: /data/beegfs/mgmtd
        mgmtd_auth_file_path: "{{ auth_file }}"

    - name: Deploy Metadata Service
      ansible.builtin.include_role:
        name: e4_computer_engineering.beegfs.metad
      vars:
        metad_beegfs_version: "{{ beegfs_version }}"
        metad_auth_file_path: "{{ auth_file }}"
        metad_server_targets:
          - target_id: "1"
            device: "sdb"
            sys_mgmtd_host: "{{ mgmt_host }}"

    - name: Deploy Storage Service
      ansible.builtin.include_role:
        name: e4_computer_engineering.beegfs.storaged
      vars:
        storaged_beegfs_version: "{{ beegfs_version }}"
        storaged_auth_file_path: "{{ auth_file }}"
        storaged_server_targets:
          - target_id: "1"
            device: "sdc"
            sys_mgmtd_host: "{{ mgmt_host }}"

    - name: Deploy Client
      ansible.builtin.include_role:
        name: e4_computer_engineering.beegfs.client
      vars:
        client_beegfs_version: "{{ beegfs_version }}"
        client_auth_file_path: "{{ auth_file }}"
        client_clusters:
          - sys_mgmtd_host: "{{ mgmt_host }}"
