---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Delete instance via server module
      openstack.cloud.server:
        name: "{{ item.name }}"
        state: absent
        delete_ips: true
        validate_certs: "{{ item.validate_certs }}"
      register: server_delete
      loop: "{{ molecule_yml.platforms }}"

    - name: Delete instance volumes
      openstack.cloud.volume:
        name: "{{ item.1 }}"
        state: absent
      loop: "{{ molecule_yml.platforms | subelements('volumes') }}"

    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: {}

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
      when: server.changed | default(false) | bool  # noqa no-handler
