---
argument_specs:

  main:
    short_description: Configure Beegfs base system
    description:
      - Prepare the base system for running Beegfs services.
    author:
      - Davide Obbi
    version_added: "1.0.0"
    options:
      system_beegfs_version:
        type: str
        description: The Beegfs version that will be used https://doc.beegfs.io/latest/release_notes.html
        required: true
        choices: ["7.4.1", "7.4.2", "7.4.3", "7.4.4", "7.4.5"]
      system_repo_gpg_keys:
        type: str
        description: Beegfs repository GPG key URL
        default: "https://www.beegfs.io/release/beegfs_{{ system_beegfs_version }}/gpg/GPG-KEY-beegfs"
      system_repo_url:
        type: str
        description: Custom Beegfs repository package repository, if not specified, upstream is used
      system_packages:
        type: list
        description: List of packages to be installed
        default: []
      system_deploy_auth_file:
        type: bool
        description:
          - Deploy the connection auth file.
          - See `system_auth_file_path` for specifying the location of the auth file to deploy.
          - WARNING do not use the authfile provided in this role
        default: true
      system_auth_file_path:
        type: str
        description: The location on local filesystem to deploy the connection auth file from
        default: "{{ role_path }}/files/connauthfile"
      system_selinux_state:
        type: str
        description:
          - Beegfs wants SElinux disabled unless configured accordingly.
          - If the task configuring SELinux has changed, the node is rebooted.
        default: disabled
        choices: ["disabled", "enforcing", "permissive"]
