---
- name: Ensure Beegfs monitoring configuration file
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/beegfs/{{ item }}"
    backup: true
    mode: "0640"
    owner: root
    group: root
  loop:
    - beegfs-mon.conf
    - beegfs-mon.auth
  notify:
    - Restart beegfs mon service
  tags:
    - mon
    - mon_configure
    - configure

- name: Enable and start Beegfs mon service
  ansible.builtin.systemd:
    name: "beegfs-mon"
    enabled: true
    state: started
  when:
    - mon_start_services
  tags:
    - mon
    - mon_run
    - run
