---
galaxy_info:
  author: Davide Obbi
  namespace: e4_computer_engineering
  description: Beegfs common configuration role
  company: E4 company

  license: license Apache-2.0

  min_ansible_version: "2.1"

  galaxy_tags:
    - beegfs
    - storage

dependencies: []
