---
cluster_storage_nodes: []
cluster_meta_nodes: []
cluster_dir_paths: []

# Beegfs defaults striping policy
cluster_dir_chunk_size: 512K
cluster_dir_num_targets: 4
cluster_dir_pattern: raid0
cluster_dir_storagepool_id: 1
