---
- name: Execute storage pools
  ansible.builtin.import_tasks: storage_pools.yml
  run_once: true

- name: Execute buddy mirror
  ansible.builtin.import_tasks: buddy_mirror.yml
  run_once: true

- name: Execute beegfs client
  ansible.builtin.import_role:
    name: client
    tasks_from: run
  vars:
    # We need the client mounting the Beegfs storage to execute setpattern command
    client_start_service: true

- name: Execute dir layout
  ansible.builtin.import_tasks: dir_layout.yml
  when: client_clusters | subelements('cluster_dir_paths', skip_missing=True) | length > 0
