---
- name: Configure
  ansible.builtin.include_role:
    # name: e4_computer_engineering.beegfs._common
    name: _common
    tasks_from: configure.yml
  vars:
    _common_service_name: "meta"
    _common_server_targets: "{{ metad_server_targets }}"
    _common_auth_file_path: "{{ metad_auth_file_path }}"
    _common_start_services: "{{ metad_start_services }}"
    _common_deploy_auth_file: "{{ metad_deploy_auth_file }}"
    _common_conn_interfaces: "{{ metad_conn_interfaces }}"
  tags:
    - metad_configure

- name: Ensure Beegfs metadata configuration files
  become: true
  ansible.builtin.template:
    src: "beegfs-meta.conf.j2"
    dest: "/etc/beegfs/inst{{ settings.target_id }}.d/beegfs-meta.conf"
    mode: "0640"
    owner: root
    group: root
  vars:
    settings: "{{ item }}"
  loop: "{{ metad_server_targets }}"
  loop_control:
    label: "/etc/beegfs/inst{{ settings.target_id }}.d/beegfs-meta.conf"
  notify:
    - Restart beegfs meta@ services
  tags:
    - metad
    - metad_configure
    - configure

- name: Check if storage data folder/s are empty before proceeding
  become: true
  ansible.builtin.find:
    paths: "/data/beegfs/beegfs_meta/t{{ item.target_id }}/dir"
    excludes: "lost+found"
  register: metad_target_dirs_content
  loop: "{{ metad_server_targets }}"
  loop_control:
    label: "/data/beegfs/beegfs_meta/t{{ item.target_id }}"
  tags:
    - metad
    - metad_configure
    - configure

- name: Execute metadata setup command
  become: true
  ansible.builtin.command: |
      /opt/beegfs/sbin/beegfs-setup-meta -C -u \
      -c /etc/beegfs/inst{{ item.item.target_id }}.d/beegfs-meta.conf \
      -p /data/beegfs/beegfs_meta/t{{ item.item.target_id }}/dir \
      -s {{ item.item.target_id }} \
      -S {{ inventory_hostname_short }}-inst{{ item.item.target_id }} \
      -m {{ item.item.sys_mgmtd_host }}
  changed_when: false
  when:
    - item.matched == 0
  loop: "{{ metad_target_dirs_content.results }}"
  loop_control:
    label: |
      /opt/beegfs/sbin/beegfs-setup-meta -C -u \
      -c /etc/beegfs/inst{{ item.item.target_id }}.d/beegfs-meta.conf \
      -p /data/beegfs/beegfs_meta/t{{ item.item.target_id }}/dir \
      -s {{ item.item.target_id }} \
      -S {{ inventory_hostname_short }}-inst{{ item.item.target_id }} \
      -m {{ item.item.sys_mgmtd_host }}
  tags:
    - metad
    - metad_configure
    - configure
