---
- name: Collect facts for mounted devices for metad_mounts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - hardware
  tags:
    - configure

- name: Set meta target mount facts
  ansible.builtin.set_fact:
    metad_mounts: |-
      [
      {% for tgt in metad_server_targets %}
        {% set target_directory = '/data/beegfs/beegfs_meta/t' + (tgt.target_id | string) %}
        {% set target_options = metad_filesystem_options %}
        {% set mounted = ansible_mounts | selectattr('mount', '==', target_directory) | length > 0 %}
        {
          "device_name": "{{ tgt.device }}",
          "mount_point": "{{ target_directory }}",
          "device_mounted": {{ mounted }},
          "fs_options": "{{ target_options | regex_replace(' ', '') }}"
        }{% if not loop.last %},{% endif %}
      {% endfor %}
      ]
  tags:
    - metad
    - metad_configure
    - configure

- name: Display generated meta mounts
  ansible.builtin.debug:
    var: item
  loop: "{{ metad_mounts }}"
  tags:
    - debug
    - never

- name: Purge filesystems
  become: true
  when: metad_filesystem_purge
  tags:
    - metad
    - metad_configure
    - configure
  block:

    - name: Stop beegfs meta@ services
      ansible.builtin.systemd_service:
        name: "beegfs-meta@inst{{ item.target_id }}"
        state: stopped
      loop: "{{ metad_server_targets }}"
      loop_control:
        label: "beegfs-meta@inst{{ item.target_id }}"
      tags:
        - purge

    - name: Unmount Beegfs meta targets
      ansible.posix.mount:
        path: "/data/beegfs/beegfs_meta/t{{ target.target_id }}"
        state: absent
      vars:
        target: "{{ item }}"
      loop: "{{ metad_server_targets }}"
      loop_control:
        label: "/data/beegfs/beegfs_meta/t{{ item.target_id }}"
      register: result
      retries: 3
      delay: 5
      until: result.failed == false
      tags:
        - purge

    - name: Remove Beegfs metadata directories
      ansible.builtin.file:
        path: "/data/beegfs/beegfs_meta/t{{ item.target_id }}"
        state: absent
      loop: "{{ metad_server_targets }}"
      loop_control:
        label: "/data/beegfs/beegfs_meta/t{{ item.target_id }}"
      tags:
        - purge

    - name: Clean all meta targets using e2fsck
      ansible.builtin.command:
        e2fsck -f /dev/{{ target.device }} -y
      vars:
        target: "{{ item }}"
      loop: "{{ metad_server_targets }}"
      loop_control:
        label: "/data/beegfs/beegfs_meta/t{{ item.target_id }}"
      changed_when: false
      tags:
        - purge

- name: Display purge status
  ansible.builtin.debug:
    var: metad_filesystem_purge
  tags:
    - debug
    - never

- name: Create filesystem on each meta targets
  become: true
  community.general.filesystem:
    fstype: "{{ metad_filesystem_type }}"
    dev: "/dev/{{ target.device_name }}"
    force: "{{ metad_filesystem_purge }}"
    opts: >
      -i {{ metad_filesystem_bytes_per_inode }} -I {{ metad_filesystem_inode_size }}
      -J size={{ metad_filesystem_journal_size }} -O {{ metad_filesystem_features }}
  vars:
    target: "{{ item }}"
  when: not target.device_mounted
  loop: "{{ metad_mounts }}"
  loop_control:
    label: "{{ target.mount_point }}"
  tags:
    - storaged
    - storaged_configure
    - configure

- name: Collect mounted devices for fs UUIDs
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - hardware
  tags:
    - configure

- name: Tune2fs all meta targets
  become: true
  ansible.builtin.command: |
      tune2fs -o user_xattr /dev/{{ target.device_name }} \
      -U {{ ansible_facts['devices'][item.device_name]['links']['uuids'] | first }}
  vars:
    target: "{{ item }}"
  loop: "{{ metad_mounts }}"
  changed_when: false
  when: not target.device_mounted
  tags:
    - configure

- name: Display device UUIDs
  ansible.builtin.debug:
    msg: "UUID={{ ansible_facts['devices'][item.device_name]['links']['uuids'] | first }}"
  loop: "{{ metad_mounts }}"
  tags:
    - debug
    - never

- name: Mount Beegfs meta targets
  become: true
  ansible.posix.mount:
    path: "{{ target.mount_point }}"
    src: "UUID={{ ansible_facts['devices'][item.device_name]['links']['uuids'] | first }}"
    fstype: "{{ metad_filesystem_type }}"
    opts: "{{ target.fs_options }}"
    state: mounted
  vars:
    target: "{{ item }}"
  loop: "{{ metad_mounts }}"
  loop_control:
    label: "{{ target.mount_point }}"
  tags:
    - metad
    - metad_configure
    - configure

- name: Create Beegfs metadata directories
  become: true
  ansible.builtin.file:
    path: "/data/beegfs/beegfs_meta/t{{ item.target_id }}/dir"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop: "{{ metad_server_targets }}"
  loop_control:
    label: "/data/beegfs/beegfs_meta/t{{ item.target_id }}"
  tags:
    - metad
    - metad_configure
    - configure
