---
- name: TLS
  ansible.builtin.include_role:
    name: _common
    tasks_from: tls.yml
  vars:
    # Warning AT the moment we do not support multimode for beegfs tool
    _common_sys_mgmtd_host: "{{ item.sys_mgmtd_host }}"
    _common_tls_tmp_dir: "{{ client_tls_tmp_dir }}"
    _common_tls_key_file: "{{ client_tls_key_file }}"
    _common_tls_cert_file: "{{ client_tls_cert_file }}"
  loop: "{{ client_clusters }}"
  when:
    - client_enable_tls | bool
    - client_beegfs_version | split('.') | first | int == 8
  tags:
    - client
    - client_configure
    - configure

- name: Ensure Beegfs autobuild configuration file
  become: true
  ansible.builtin.template:
    src: "beegfs-client-autobuild.conf.j2"
    dest: "/etc/beegfs/beegfs-client-autobuild.conf"
    mode: "0640"
    owner: root
    group: root
  when:
    - not client_dkms_install
  tags:
    - client
    - client_configure
    - configure

- name: Ensure Beegfs helperd configuration file
  become: true
  ansible.builtin.template:
    src: "beegfs-helperd.conf.j2"
    dest: "/etc/beegfs/beegfs-helperd.conf"
    backup: true
    owner: root
    mode: "0640"
    group: root
  loop: "{{ client_clusters }}"
  loop_control:
    label: "{{ item.sys_mgmtd_host }}"
  when:
    - not multi_mode
    - client_beegfs_version | split('.') | first | int == 7
  notify:
    - Restart beegfs helperd service
  tags:
    - client
    - client_configure
    - configure

- name: Ensure Beegfs client configuration file
  become: true
  ansible.builtin.template:
    src: "beegfs-client.conf.j2"
    dest: "/etc/beegfs/beegfs-client.conf"
    backup: true
    mode: "0640"
    owner: root
    group: root
  loop: "{{ client_clusters }}"
  loop_control:
    label: "{{ item.sys_mgmtd_host }}"
  when: not multi_mode
  notify:
    - Restart beegfs client service
  tags:
    - client
    - client_configure
    - configure

- name: Ensure Beegfs service environment variables file
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/default/{{ item }}"
    group: root
    mode: "0640"
  loop:
    - beegfs-client
    - beegfs-helperd
  notify:
    - Restart beegfs client service
    - Restart beegfs helperd service
  tags:
    - client
    - client_configure
    - configure

- name: Disable and mask canonical Beegfs client services
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    masked: true
  loop:
    - beegfs-helperd.service
    - beegfs-client.service
  when: multi_mode
  tags:
    - client
    - client_configure
    - configure

- name: Create Beegfs per cluster configuration directories
  become: true
  ansible.builtin.file:
    path: "/etc/beegfs/{{ item.sys_mgmtd_host | replace('-', '') }}.d"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop: "{{ client_clusters }}"
  loop_control:
    label: "/etc/beegfs/{{ item.sys_mgmtd_host | replace('-', '') }}.d"
  when: multi_mode
  tags:
    - client
    - client_configure
    - configure

- name: Ensure Beegfs helperd configuration files for multimode deployment
  become: true
  ansible.builtin.template:
    src: "beegfs-helperd.conf.j2"
    dest: "/etc/beegfs/{{ item.sys_mgmtd_host | replace('-', '') }}.d/beegfs-helperd.conf"
    mode: "0640"
    owner: root
    group: root
  loop: "{{ client_clusters }}"
  loop_control:
    label: "/etc/beegfs/{{ item.sys_mgmtd_host | replace('-', '') }}.d/beegfs-helperd.conf"
  when:
    - multi_mode
    - client_beegfs_version | split('.') | first | int == 7
  notify:
    - Restart beegfs helperd@ services
  tags:
    - client
    - client_configure
    - configure

- name: Ensure Beegfs mounts configuration file for multimode deployment
  become: true
  ansible.builtin.template:
    src: "beegfs-mounts.conf.j2"
    dest: "/etc/beegfs/{{ item.sys_mgmtd_host | replace('-', '') }}.d/beegfs-mounts.conf"
    mode: "0640"
    owner: root
    group: root
  loop: "{{ client_clusters }}"
  loop_control:
    label: "/etc/beegfs/{{ item.sys_mgmtd_host | replace('-', '') }}.d/beegfs-mounts.conf"
  when:
    - multi_mode
    - not client_dkms_install
  # WARNING: at the moment i can't think of a way to restart only the changed cluster service
  notify:
    - Restart beegfs client@ services
  tags:
    - client
    - client_configure
    - configure

- name: Ensure interfaces list file is present for multimode deployment
  become: true
  ansible.builtin.template:
    src: conn_interfaces_file.j2
    dest: "/etc/beegfs/{{ settings.sys_mgmtd_host | replace('-', '') }}.d/client_interfaces"
    owner: root
    group: root
    mode: "0640"
  vars:
    settings: "{{ item }}"
  loop: "{{ client_clusters }}"
  loop_control:
    label: "{{ settings.conn_interfaces | default(client_conn_interfaces) }}"
  when:
    - multi_mode
    - settings.conn_interfaces is defined
    - settings.conn_interfaces | length > 0
  tags:
    - client
    - client_configure
    - configure

- name: Ensure Beegfs client configuration files for multimode deployment
  become: true
  ansible.builtin.template:
    src: "beegfs-client.conf.j2"
    dest: "/etc/beegfs/{{ item.sys_mgmtd_host | replace('-', '') }}.d/beegfs-client.conf"
    mode: "0640"
    owner: root
    group: root
  loop: "{{ client_clusters }}"
  loop_control:
    label: "/etc/beegfs/{{ item.sys_mgmtd_host | replace('-', '') }}.d/beegfs-client.conf"
  when: multi_mode
  # WARNING: at the moment i can't think of a way to restart only the changed cluster service
  notify:
    - Restart beegfs client@ services
  tags:
    - client
    - client_configure
    - configure

- name: Ensure Beegfs modules configuration file
  become: true
  ansible.builtin.copy:
    dest: "/etc/modules-load.d/beegfs-client-dkms.conf"
    content: beegfs
    mode: "0644"
    owner: root
    group: root
  when:
    - client_dkms_install
  notify:
    - Load beegfs module
  tags:
    - client
    - client_configure
    - configure

# As per Beegfs DKMS documentation this file needs to exists before installing the beegfs-client-dkms
- name: Ensure The Beegfs client DKMS build
  become: true
  when:
    - client_dkms_install
  tags:
    - client
    - client_configure
    - configure
    - install
    - client_install
  block:
    - name: Ensure Beegfs client build DKMS configuration file
      ansible.builtin.template:
        src: "beegfs-client-build.mk.j2"
        dest: "/etc/beegfs/beegfs-client-build.mk"
        mode: "0640"
        owner: root
        group: root

    - name: Install beegfs-client-dkms package
      ansible.builtin.package:
        name: beegfs-client-dkms
        state: present
      register: _package_inst
      retries: 3
      until: _package_inst is success

- name: Enable and start per cluster Beegfs helperd service
  become: true
  ansible.builtin.systemd:
    name: "beegfs-helperd"
    enabled: true
    state: started
  when:
    - not multi_mode
    - client_dkms_install
    - client_beegfs_version | split('.') | first | int == 7
  tags:
    - configure
    - client
    - client_configure

- name: Enable and start per cluster Beegfs helperd services for multimode deployment
  become: true
  ansible.builtin.systemd:
    name: "beegfs-helperd@{{ item.sys_mgmtd_host | replace('-', '') }}"
    enabled: true
    state: started
  loop: "{{ client_clusters }}"
  loop_control:
    label: "beegfs-helperd@{{ item.sys_mgmtd_host | replace('-', '') }}"
  when:
    - multi_mode
    - client_dkms_install
    - client_beegfs_version | split('.') | first | int == 7
  tags:
    - configure
    - client
    - client_configure

- name: Mount Beegfs DKMS client filesystem
  become: true
  ansible.posix.mount:
    src: beegfs_nodev
    path: /mnt/beegfs
    fstype: beegfs
    opts: rw,relatime,cfgFile=/etc/beegfs/beegfs-client.conf,_netdev,x-systemd.after=beegfs-helperd,nofail
    state: mounted
  when:
    - client_dkms_install
    - not multi_mode
  tags:
    - configure
    - client
    - client_configure

- name: Mount Beegfs DKMS client filesystem for multimode deployment
  become: true
  ansible.posix.mount:
    src: beegfs_nodev
    path: /mnt/beegfs
    fstype: beegfs
    opts: "rw,relatime,\
           cfgFile=/etc/beegfs/{{ item.sys_mgmtd_host | replace('-', '') }}.d/beegfs-client.conf,\
           _netdev,x-systemd.after=beegfs-helperd,nofail"
    state: mounted
  loop: "{{ client_clusters }}"
  loop_control:
    label: "rw,relatime,\
            cfgFile=/etc/beegfs/{{ item.sys_mgmtd_host | replace('-', '') }}.d/beegfs-client.conf,\
            _netdev,x-systemd.after=beegfs-helperd,nofail"
  when:
    - client_dkms_install
    - multi_mode
  tags:
    - configure
    - client
    - client_configure
