---
- name: Populate service facts
  ansible.builtin.service_facts:
  tags:
    - client
    - client_configure
    - configure

- name: Create filesystem mount point directories
  become: true
  ansible.builtin.file:
    path: "{{ item.1.fs_path }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop: "{{ client_clusters | subelements('client_dir_paths', skip_missing=True) }}"
  when:
    - item.1.fs_path is defined
  tags:
    - client
    - client_configure
    - configure

- name: Ensure Beegfs hook script file
  become: true
  ansible.builtin.template:
    src: "beegfs-client-mount-hook.sh.j2"
    dest: "/etc/beegfs/beegfs-client-mount-hook.sh"
    mode: "0750"
    owner: root
    group: root
  loop: "{{ client_clusters }}"
  loop_control:
    label: "{{ item.sys_mgmtd_host }}"
  when:
    - not multi_mode
  notify:
    - Restart beegfs client service
  tags:
    - client
    - client_configure
    - configure

- name: Ensure Beegfs client service file for custom mounts
  become: true
  ansible.builtin.template:
    src: "beegfs-client.service.j2"
    dest: "/usr/lib/systemd/system/beegfs-client.service"
    mode: "640"
    owner: root
    group: root
  when:
    - not multi_mode
    - not client_dkms_install
  notify:
    - Restart beegfs client service
  tags:
    - client
    - client_configure
    - configure

- name: Ensure Beegfs hook script file for multi mode deployment
  become: true
  ansible.builtin.template:
    src: "beegfs-client-mount-hook.sh.j2"
    dest: "/etc/beegfs/{{ item.sys_mgmtd_host | replace('-', '') }}.d/beegfs-client-mount-hook.sh"
    mode: "0750"
    owner: root
    group: root
  loop: "{{ client_clusters }}"
  loop_control:
    label: "/etc/beegfs/{{ item.sys_mgmtd_host | replace('-', '') }}.d/beegfs-client-mount-hook.sh"
  when:
    - multi_mode
    - item.client_dir_paths is defined
  # WARNING: at the moment i can't think of a way to restart only the changed cluster service
  notify:
    - Restart beegfs client@ services
  tags:
    - client
    - client_configure
    - configure

- name: Ensure Beegfs client service file for custom mounts and multi mode deployment
  become: true
  ansible.builtin.template:
    src: "beegfs-client.service.j2"
    dest: "/usr/lib/systemd/system/beegfs-client@.service"
    mode: "0640"
    owner: root
    group: root
  when:
    - multi_mode
    - not client_dkms_install
  notify:
    - Restart beegfs client@ services
  tags:
    - client
    - client_configure
    - configure

- name: Ensure Beegfs is mounted
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "beegfs-client"
    state: started
  when:
    - client_start_services
    - not multi_mode
    - not client_dkms_install
    - not ansible_check_mode
  tags:
    - client
    - client_configure
    - configure

- name: Ensure Beegfs is mounted
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "beegfs-client@{{ item.sys_mgmtd_host | replace('-', '') }}"
    state: started
  loop: "{{ client_clusters }}"
  when:
    - client_start_services
    - multi_mode
    - not client_dkms_install
    - not ansible_check_mode
  tags:
    - client
    - client_configure
    - configure


- name: Create Beegfs user mount point directories for single cluster deployment
  become: true
  ansible.builtin.file:
    path: "/mnt/beegfs/{{ item.1.beegfs_path }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop: "{{ client_clusters | subelements('client_dir_paths', skip_missing=True) }}"
  loop_control:
    label: "/mnt/beegfs/{{ item.1.beegfs_path }}"
  when:
    - client_start_services
    - not multi_mode
  run_once: true
  tags:
    - client
    - client_configure
    - configure

- name: Create Beegfs user mount point directories for multimode deployment
  become: true
  ansible.builtin.file:
    path: "/mnt/beegfs/{{ item.0.sys_mgmtd_host | replace('-', '') }}/{{ item.1.beegfs_path }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop: "{{ client_clusters | subelements('client_dir_paths', skip_missing=True) }}"
  loop_control:
    label: "/mnt/beegfs/{{ item.0.sys_mgmtd_host | replace('-', '') }}/{{ item.1.beegfs_path }}"
  when:
    - client_start_services
    - multi_mode
  run_once: true
  tags:
    - client
    - client_configure
    - configure
