---
- name: Enable and start per cluster Beegfs helperd service
  become: true
  ansible.builtin.systemd:
    name: "beegfs-helperd"
    enabled: true
    state: started
  when:
    - not multi_mode
    - client_start_services
    - client_beegfs_version | split('.') | first | int == 7
    - not ansible_check_mode
  tags:
    - client
    - client_run
    - run

- name: Enable and start per cluster Beegfs client service
  become: true
  ansible.builtin.systemd:
    name: "beegfs-client"
    enabled: true
    state: started
  when:
    - not multi_mode
    - client_start_services
    - not client_dkms_install
    - not ansible_check_mode
  tags:
    - client
    - client_run
    - run

- name: Enable and start per cluster Beegfs helperd services for multimode deployment
  become: true
  ansible.builtin.systemd:
    name: "beegfs-helperd@{{ item.sys_mgmtd_host | replace('-', '') }}"
    enabled: true
    state: started
  loop: "{{ client_clusters }}"
  loop_control:
    label: "beegfs-helperd@{{ item.sys_mgmtd_host | replace('-', '') }}"
  when:
    - multi_mode
    - client_start_services
    - beegfs
    - client_beegfs_version | split('.') | first | int == 7
    - not ansible_check_mode
  tags:
    - client
    - client_run
    - run

- name: Enable and start per cluster Beegfs client services for multimode deployment
  become: true
  ansible.builtin.systemd:
    name: "beegfs-client@{{ item.sys_mgmtd_host | replace('-', '') }}"
    enabled: true
    state: started
  loop: "{{ client_clusters }}"
  loop_control:
    label: "beegfs-client@{{ item.sys_mgmtd_host | replace('-', '') }}"
  when:
    - multi_mode
    - client_start_services
    - not client_dkms_install
    - not ansible_check_mode
  tags:
    - client
    - client_run
    - run
