---
- name: Create Beegfs mgmtd data directories
  ansible.builtin.file:
    path: "{{ mgmtd_store_mgmtd_directory }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  tags:
    - mgmtd
    - mgmtd_configure
    - configure

- name: Ensure interfaces list file is present
  ansible.builtin.template:
    src: conn_interfaces_file.j2
    dest: "/etc/beegfs/mgmtd_interfaces"
    owner: root
    group: root
    mode: "0640"
  when:
    - mgmtd_conn_interfaces | length > 0
  tags:
    - mgmtd
    - mgmtd_configure
    - configure

- name: Ensure Beegfs management configuration file
  ansible.builtin.template:
    src: "beegfs-mgmtd.conf.j2"
    dest: "/etc/beegfs/beegfs-mgmtd.conf"
    backup: true
    mode: "0640"
    owner: root
    group: root
  notify:
    - Restart beegfs mgmtd service
  tags:
    - mgmtd
    - mgmtd_configure
    - configure

- name: Check if management data folder is empty before proceeding
  ansible.builtin.find:
    paths: "{{ mgmtd_store_mgmtd_directory }}"
    excludes: "lost+found"
  register: mgmtd_target_dir_content
  tags:
    - configure

- name: Execute management setup command for single cluster deployment
  ansible.builtin.command: |
    /opt/beegfs/sbin/beegfs-setup-mgmtd -C -p {{ mgmtd_store_mgmtd_directory }} -S {{ mgmtd_string_id }}
  changed_when: false
  when:
    - mgmtd_target_dir_content.matched == 0
  tags:
    - mgmtd
    - mgmtd_configure
    - configure

- name: Enable and start per cluster Beegfs mgmtd service
  ansible.builtin.systemd:
    name: "beegfs-mgmtd"
    enabled: true
    state: started
  when:
    - mgmtd_start_services
  tags:
    - mgmtd
    - mgmtd_run
    - run
