---
- name: Ensure Beegfs management configuration file
  become: true
  ansible.builtin.template:
    src: "beegfs-mgmtd.toml.j2"
    dest: "/etc/beegfs/beegfs-mgmtd.toml"
    backup: true
    mode: "0640"
    owner: root
    group: root
  notify:
    - Restart beegfs mgmtd service
  tags:
    - mgmtd
    - mgmtd_configure
    - configure

- name: Copy license file
  become: true
  ansible.builtin.copy:
    src: "{{ mgmtd_license_file_path }}"
    dest: /etc/beegfs/license.pem
    owner: root
    group: root
    mode: "0400"
  when:
    - mgmtd_license_disable == "false"
  tags:
    - mgmtd
    - mgmtd_configure
    - configure

- name: Check if management dir is empty before proceeding
  become: true
  ansible.builtin.find:
    paths: "{{ mgmtd_store_mgmtd_directory }}"
    excludes: "lost+found"
  register: _mgmtd_target_dir_content
  tags:
    - mgmtd
    - mgmtd_configure
    - configure

- name: Execute management setup command
  become: true
  ansible.builtin.command: |
    /opt/beegfs/sbin/beegfs-mgmtd --init
  changed_when: false
  when:
    - _mgmtd_target_dir_content.matched == 0
  tags:
    - mgmtd
    - mgmtd_configure
    - configure

- name: TLS
  ansible.builtin.include_role:
    # name: e4_computer_engineering.beegfs._common
    name: _common
    tasks_from: tls.yml
  vars:
    _common_sys_mgmtd_host: "{{ ansible_hostname }}"
    _common_tls_tmp_dir: "{{ mgmtd_tls_tmp_dir }}"
    _common_tls_key_file: "{{ mgmtd_tls_key_file }}"
    _common_tls_cert_file: "{{ mgmtd_tls_cert_file }}"
  when:
    - mgmtd_enable_tls | bool
  tags:
    - mgmtd
    - mgmtd_configure
    - configure
