---
- name: Configure Beegfs Metadata
  gather_facts: false
  hosts: '{{ meta_nodes | default("metadata") }}'
  tasks:
    - name: Import Beegfs metad role
      ansible.builtin.import_role:
        name: metad
