---
- name: Configure Beegfs Management
  gather_facts: false
  hosts: '{{ mgmt_node |default("management") }}'
  tasks:
    - name: Import Beegfs mgmtd role
      ansible.builtin.import_role:
        name: mgmtd
