---
- name: Configure Beegfs Monitoring
  gather_facts: false
  hosts: '{{ mon_nodes |default("monitoring") }}'
  tasks:
    - name: Import Beegfs mon role
      ansible.builtin.import_role:
        name: mon
