---
- name: Configure Beegfs Storage
  gather_facts: false
  hosts: '{{ storage_nodes | default("storage") }}'
  tasks:
    - name: Import Beegfs storaged role
      ansible.builtin.import_role:
        name: storaged
