---
- name: Configure Beegfs Storage
  become: true
  gather_facts: false
  hosts: '{{ storage_nodes | default("all") }}'
  tasks:
    - name: Import Beegfs storaged role
      ansible.builtin.import_role:
        name: storaged
