---
storaged_start_services: true
storaged_server_targets: []

# Filesystem specs
storaged_filesystem_type: "xfs"
storaged_filesystem_strip_unit: "128k"
storaged_filesystem_strip_width: 8
storaged_filesystem_log_version: 2
storaged_filesystem_log_bufs: 8
storaged_filesystem_log_unit: "128k"
storaged_filesystem_inode_size: 512
storaged_filesystem_alloc_size: "131072k"
storaged_filesystem_options: >-
  defaults,noatime,nodiratime,seclabel,swalloc,attr2,largeio,inode64,nofail,
  allocsize={{ storaged_filesystem_alloc_size }},
  logbufs={{ storaged_filesystem_log_bufs }},
  logbsize={{ storaged_filesystem_log_unit }}
storaged_filesystem_quota_options: ",uqnoenforce,gqnoenforce"
storaged_filesystem_purge: false


# /etc/beegfs/beegfs-storage.conf
storaged_target_id: "1"
storaged_sys_mgmtd_host: localhost
storaged_conn_mgmtd_port_tcp: "8008"
storaged_conn_mgmtd_port_udp: "8008"
storaged_conn_storage_port_tcp: "8003"
storaged_conn_storage_port_udp: "8003"
storaged_conn_rdma_buf_size: "8192"
storaged_conn_rdma_buf_num: "70"
storaged_log_type: "syslog"
storaged_sys_target_offline_timeout_secs: "180"
storaged_tune_file_read_size: 1024k
storaged_tune_file_write_size: 1024k
storaged_tune_num_workers: "12"
storaged_quota_enable_enforcement: "false"
storaged_conn_interfaces: []

storaged_storagepool_id: "1"
storaged_mirrorgroup_id: ""
storaged_storagepool_desc: ""
