---
name: Collection Docs Push

concurrency:
  group: docs-push-${{ github.sha }}
  cancel-in-progress: true
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    tags:
      - '*'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-docs:
    permissions:
      contents: read
    name: Build Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-push.yml@main
    with:
      init-lenient: false
      init-fail-on-error: true
      collection-name: e4.beegfs
      squash-hierarchy: true
      init-project: E4.Beegfs Collection
      init-copyright: E4.Beegfs Contributors
      init-title: E4.Beegfs Collection Documentation
      init-html-short-title: E4.Beegfs Collection Docs
      # yamllint disable-line rule:line-length
      init-extra-html-theme-options: documentation_home_url=https://${{ github.repository_owner }}.github.io/${{github.event.repository.name }}/branch/main/

  publish-docs-gh-pages:
    # use to prevent running on forks
    if: github.repository == 'E4-Computer-Engineering/beegfs-ansible'
    permissions:
      contents: write
    needs: [build-docs]
    name: Publish Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-publish-gh-pages.yml@main
    with:
      artifact-name: ${{ needs.build-docs.outputs.artifact-name }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
