---
- name: Configure
  ansible.builtin.include_role:
    name: _common
    tasks_from: configure.yml
  vars:
    _common_service_name: "storage"
    _common_server_targets: "{{ storaged_server_targets }}"
    _common_auth_file_path: "{{ storaged_auth_file_path }}"
    _common_start_services: "{{ storaged_start_services }}"
    _common_deploy_auth_file: "{{ storaged_deploy_auth_file }}"
    _common_conn_interfaces: "{{ storaged_conn_interfaces }}"
  tags:
    - storaged
    - storaged_configure
    - configure

- name: Ensure Beegfs storage configuration files
  become: true
  ansible.builtin.template:
    src: "beegfs-storage.conf.j2"
    dest: "/etc/beegfs/inst{{ settings.target_id }}.d/beegfs-storage.conf"
    mode: "0640"
    owner: root
    group: root
  vars:
    settings: "{{ item }}"
  loop: "{{ storaged_server_targets }}"
  loop_control:
    label: "/etc/beegfs/inst{{ settings.target_id }}.d/beegfs-storage.conf"
  notify:
    - Restart beegfs storage@ services
  tags:
    - storaged
    - storaged_configure
    - configure

- name: Check if storage data folder/s are empty before proceeding
  become: true
  ansible.builtin.find:
    paths: "/data/beegfs/beegfs_storage/t{{ item.target_id }}/dir"
    excludes: "lost+found"
  register: storaged_target_dirs_content
  loop: "{{ storaged_server_targets }}"
  loop_control:
    label: "/data/beegfs/beegfs_storage/t{{ item.target_id }}"
  tags:
    - storaged
    - storaged_configure
    - configure

- name: Execute storage setup command
  become: true
  ansible.builtin.command: |
      /opt/beegfs/sbin/beegfs-setup-storage -C -u \
      -c /etc/beegfs/inst{{ item.item.target_id }}.d/beegfs-storage.conf \
      -p /data/beegfs/beegfs_storage/t{{ item.item.target_id }}/dir \
      -s {{ item.item.target_id }} \
      -i {{ item.item.target_id }} \
      -I {{ inventory_hostname_short }}-t{{ item.item.target_id }} \
      -S {{ inventory_hostname_short }}-inst{{ item.item.target_id }} \
      -m {{ item.item.sys_mgmtd_host }}
  changed_when: false
  when:
    - item.matched == 0
  loop: "{{ storaged_target_dirs_content.results }}"
  loop_control:
    label: |
      /opt/beegfs/sbin/beegfs-setup-storage -C -u \
      -c /etc/beegfs/inst{{ item.item.target_id }}.d/beegfs-storage.conf \
      -p /data/beegfs/beegfs_storage/t{{ item.item.target_id }}/dir \
      -s {{ item.item.target_id }} \
      -i {{ item.item.target_id }} \
      -I {{ inventory_hostname_short }}-t{{ item.item.target_id }} \
      -S {{ inventory_hostname_short }}-inst{{ item.item.target_id }} \
      -m {{ item.item.sys_mgmtd_host }}
  tags:
    - storaged
    - storaged_configure
    - configure
